language: csharp
solution: bodite-render.sln
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mono
  - sudo apt-get install -y fsharp
  - sudo apt-get install -y nuget
  - sudo apt-get install -y nunit-console
install:
  - nuget restore
script:
  - xbuild /p:Configuration=Release
  - nunit-console ./BoditeRender.Lib.Tests/bin/Release/BoditeRender.Lib.Tests.dll
 
