sudo: required
language: fsharp
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mono-complete
  - sudo apt-get install -y fsharp
  - sudo apt-get install -y nuget
  - sudo apt-get install -y nunit-console
install:
  - nuget restore bodite-render.sln
  - xbuild /p:Configuration=Release bodite-render.sln
script:
  - nunit-console ./BoditeRender.Lib.Tests/bin/Release/BoditeRender.Lib.Tests.dll 
