sudo: required
language: Javascript
dist: trusty
services:
  - docker
install:
  - docker build -t bbr .
  - docker create -it --name=bbr bbr
  - docker ps -a
script:
  - docker start bbr
  - docker exec bbr bash -c "nunit-console /bb/BoditeRender.Lib.Tests/bin/Release/BoditeRender.Lib.Tests.dll"
