sudo: required
services:
  - docker
addons:
  - apt:
    - sources:
    - packages:
      - mono
      - fsharp
      - nuget
      - nunit-console
install:
  - nuget restore bodite-render.sln
script:
  - xbuild /p:Configuration=Release bodite-render.sln
  - nunit-console ./BoditeRender.Lib.Tests/bin/Release/BoditeRender.Lib.Tests.dll 
