sudo: false
addons:
  apt:
    sources:
      - mono
    packages:
      - mono-complete
      - fsharp
      - nuget
      - nunit-console
language:
  - F#
install:
  - nuget restore bodite-render.sln
script:
  - xbuild /p:Configuration=Release bodite-render.sln
  - nunit-console ./BoditeRender.Lib.Tests/bin/Release/BoditeRender.Lib.Tests.dll 
