language: csharp
mono:
  - 3.12.0
solution: bodite-render.sln
install:
  - nuget restore bodite-render.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release bodite-render.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./BoditeRender.Lib.Tests/bin/Release/BoditeRender.Lib.Tests.dll 
