sudo: required
language: fsharp
git:
  depth: 1
services:
  - docker
before_install:
  - docker build -t bbr .
  - docker create -it -v $(pwd):bb/src:ro bbr --name=bbr
install:
  - docker start bbr
  - docker exec bbr bash -c "echo 123456"
script:
  - nunit-console ./BoditeRender.Lib.Tests/bin/Release/BoditeRender.Lib.Tests.dll
